// Centralized route configuration
export const appRouter = {
  // Public routes
  home: "/",
  blog: "/blog",
  affiliates: "/affiliates",
  privacy: "/privacy",
  terms: "/terms",

  // Dashboard routes (protected)
  dashboard: "/d",
  accounts: "/d/accounts",
  posts: "/d/posts",
  accountsCallback: "/d/accounts/callback",
  analytics: "/d/analytics",
  business: "/d/business",
  media: "/d/media",
  settings: "/d/settings",
  billing: "/d/billing",
  onboarding: "/onboarding",

  // API routes
  api: {
    auth: "/api/auth",
    checkout: "/api/checkout",
    accounts: "/api/accounts",
    accountsConnect: "/api/accounts/connect",
    accountsDisconnect: "/api/accounts/disconnect",
    accountsRemove: "/api/accounts/remove",
    posts: "/api/posts",
    postsCounts: "/api/posts/counts",
    postsDelete: "/api/posts/delete",
    postsDetail: "/api/posts/detail",
    postsRetry: "/api/posts/retry",
    postsUnpublish: "/api/posts/unpublish",
    postsUpdate: "/api/posts/update",
    postsActions: "/api/posts/actions",
    postsCompose: "/api/posts/compose",
    accountsCallback: "/api/accounts/callback",
    suggestions: "/api/suggestions",
    chat: "/api/chat",
    billingPortal: "/api/billing/portal",
    billingChangePlan: "/api/billing/change-plan",
    billingTopup: "/api/billing/topup",
    media: "/api/media",
    mediaUpload: "/api/media/upload",
    mediaDelete: "/api/media/delete",
    uploadsSign: "/api/uploads/sign",
    userTimezone: "/api/user/timezone",
    onboardingAnalyze: "/api/onboarding/analyze",
    onboardingConfirm: "/api/onboarding/confirm",
    analytics: "/api/analytics",
    analyticsPosts: "/api/analytics/posts",
    analyticsBestTimes: "/api/analytics/best-times",
    analyticsFollowers: "/api/analytics/followers",
    analyticsChannelStats: "/api/analytics/channel-stats",
    dashboardStatus: "/api/dashboard/status",
    webhooks: {
      stripe: "/api/webhooks/stripe",
      zernio: "/api/webhooks/zernio",
    },
  },
};
