// Centralized route configuration
export const appRouter = {
  // Public routes
  home: "/",
  pricing: "/pricing",
  blog: "/blog",
  affiliates: "/affiliates",
  privacy: "/privacy",
  terms: "/terms",

  // Auth routes
  signin: "/signin",
  signup: "/signup",
  resetPassword: "/reset-password",

  // Dashboard routes (protected)
  dashboard: "/d",
  accounts: "/d/accounts",
  posts: "/d/posts",
  accountsCallback: "/d/accounts/callback",
  analytics: "/d/analytics",
  context: "/d/context",
  settings: "/d/settings",
  billing: "/d/billing",
  credits: "/d/credits",
  onboarding: "/onboarding",

  // API routes
  api: {
    auth: "/api/auth",
    checkout: "/api/checkout",
    accounts: "/api/accounts",
    accountsConnect: "/api/accounts/connect",
    accountsDisconnect: "/api/accounts/disconnect",
    accountsRemove: "/api/accounts/remove",
    posts: "/api/posts",
    postsDelete: "/api/posts/delete",
    postsDetail: "/api/posts/detail",
    postsRetry: "/api/posts/retry",
    postsUnpublish: "/api/posts/unpublish",
    postsUpdate: "/api/posts/update",
    accountsCallback: "/api/accounts/callback",
    billingPortal: "/api/billing/portal",
    billingChangePlan: "/api/billing/change-plan",
    mediaUpload: "/api/media/upload",
    transcribe: "/api/transcribe",
    userTimezone: "/api/user/timezone",
    userContext: "/api/user/context",
    onboarding: "/api/onboarding",
    chat: "/api/chat",
    chatHistory: "/api/chat/history",
    credits: "/api/credits",
    creditsCheckout: "/api/credits/checkout",
    imageGenerate: "/api/image/generate",
    analytics: "/api/analytics",
    analyticsPosts: "/api/analytics/posts",
    analyticsBestTimes: "/api/analytics/best-times",
    analyticsFollowers: "/api/analytics/followers",
    dashboardStatus: "/api/dashboard/status",
    webhooks: {
      stripe: "/api/webhooks/stripe",
      zernio: "/api/webhooks/zernio",
    },
  },
};
