export const errorMessages = {
  SERVER_ERROR: "An unexpected error occurred",
  MISSING_FIELDS: "Missing required fields",
  INVALID_WEBHOOK_PAYLOAD: "Invalid webhook payload",
  WEBHOOK_PROCESSING_FAILED: "Failed to process webhook",
  UNAUTHORIZED: "Unauthorized. Please sign in to continue",
  INVALID_PAYLOAD: "Invalid payload",
  NOT_FOUND: "Resource not found",
  USER_NOT_FOUND: "User not found",
  RATE_LIMIT_EXCEEDED: "Too many requests. Please try again later.",
  EMAIL_SEND_FAILED: "Failed to send email. Please try again.",
  PAYMENT_FAILED: "Payment processing failed. Please try again.",
  SUBSCRIPTION_NOT_FOUND: "Subscription not found",
  ALREADY_SUBSCRIBED: "You already have an active subscription.",
  PROVISIONING_FAILED: "Failed to set up your bot. Please contact support.",
  BOT_NOT_FOUND: "Bot not found. Please set up your bot first.",
  INVALID_TELEGRAM_TOKEN: "Invalid Telegram bot token format.",
  SUBSCRIPTION_REQUIRED: "An active subscription is required.",
  LATE_API_ERROR: "Failed to communicate with social media service.",
};
