export const errorMessages = {
  SERVER_ERROR: "An unexpected error occurred",
  MISSING_FIELDS: "Missing required fields",
  INVALID_WEBHOOK_PAYLOAD: "Invalid webhook payload",
  WEBHOOK_PROCESSING_FAILED: "Failed to process webhook",
  UNAUTHORIZED: "Unauthorized. Please sign in to continue",
  INVALID_PAYLOAD: "Invalid payload",
  NOT_FOUND: "Resource not found",
  USER_NOT_FOUND: "User not found",
  RATE_LIMIT_EXCEEDED: "Too many requests. Please try again later.",
  EMAIL_SEND_FAILED: "Failed to send email. Please try again.",
  PAYMENT_FAILED: "Payment processing failed. Please try again.",
  SUBSCRIPTION_NOT_FOUND: "Subscription not found",
  ALREADY_SUBSCRIBED: "You already have an active subscription.",
  PROVISIONING_FAILED: "Failed to set up your AI social media manager. Please contact support.",
  BOT_NOT_FOUND: "AI social media manager not found. Please subscribe first.",
  SUBSCRIPTION_REQUIRED: "An active subscription is required.",
  ZERNIO_API_ERROR: "Failed to communicate with social media service.",
  TRANSCRIPTION_FAILED: "Failed to transcribe audio. Please try again.",
  INSUFFICIENT_CREDITS: "Not enough credits. Purchase more to continue.",
  GENERATION_FAILED: "Image generation failed. Please try again.",
  STARTER_NO_GENERATION: "Image generation is not available on the Starter plan.",
};
