-- AlterTable: store the LLM-authored social strategy per connected account.
-- JSON (no enum) to match the codebase convention. Generated by
-- `socialStrategy.computeStrategy` after insights, and refreshed on reconnect.
-- Shape validated by `src/lib/schemas/strategy.ts` (strategyStoredSchema).
ALTER TABLE "social_account" ADD COLUMN "strategy" JSONB;
